// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pogodeo.DataAccess;

namespace Pogodeo.DataAccess.Migrations
{
    [DbContext(typeof(PogodeoAppDataContext))]
    [Migration("20180906121915_DeletedTestTableAddedNewLocalizationTable")]
    partial class DeletedTestTableAddedNewLocalizationTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pogodeo.DataAccess.CityLocalizationKeys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccuWeatherLocalizationKey");

                    b.Property<string>("CityName");

                    b.HasKey("Id");

                    b.ToTable("CityLocalizationKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
