// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pogodeo.DataAccess;

namespace Pogodeo.DataAccess.Migrations
{
    [DbContext(typeof(PogodeoAppDataContext))]
    [Migration("20180910120203_AccuWeatherWeatherTable")]
    partial class AccuWeatherWeatherTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pogodeo.DataAccess.AccuWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssociatedBigCityId");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("WeatherData");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedBigCityId");

                    b.ToTable("AccuWeatherWeather");
                });

            modelBuilder.Entity("Pogodeo.DataAccess.BigCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccuWeatherLocalizationKey");

                    b.Property<string>("CityName");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("BigCitiesData");
                });

            modelBuilder.Entity("Pogodeo.DataAccess.SmallCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssociatedBigCityId");

                    b.Property<string>("CityName");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedBigCityId");

                    b.ToTable("SmallCitiesData");
                });

            modelBuilder.Entity("Pogodeo.DataAccess.AccuWeather", b =>
                {
                    b.HasOne("Pogodeo.DataAccess.BigCity", "AssociatedBigCity")
                        .WithMany()
                        .HasForeignKey("AssociatedBigCityId");
                });

            modelBuilder.Entity("Pogodeo.DataAccess.SmallCity", b =>
                {
                    b.HasOne("Pogodeo.DataAccess.BigCity", "AssociatedBigCity")
                        .WithMany("SubordinateCities")
                        .HasForeignKey("AssociatedBigCityId");
                });
#pragma warning restore 612, 618
        }
    }
}
